apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics
  namespace: kube-observability
  labels:
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/instance: kube-state-metrics
    app.kubernetes.io/component: observability
    app.kubernetes.io/part-of: grafana
    app.kubernetes.io/managed-by: flux
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: 8080
      targetPort: http-metrics
    - name: telemetry
      port: 8081
      targetPort: telemetry
  selector:
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/instance: kube-state-metrics
