apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: foobar-api-server
  namespace: foobar
spec:
  isCA: false
  duration: 2160h
  renewBefore: 360h
  secretName: foobar-api-server
  commonName: foobar-api.foobar.svc.cluster.local
  subject:
    organizations:
      - foobar
  dnsNames:
    - foobar-api.foobar
    - foobar-api.foobar.svc
    - foobar-api.foobar.svc.cluster.local

  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048

  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: raimon
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: foobar-api-client
  namespace: foobar
spec:
  isCA: false
  duration: 2160h
  renewBefore: 360h
  secretName: foobar-api-client
  commonName: foobar-api.foobar.svc.cluster.local
  subject:
    organizations:
      - foobar
  dnsNames:
    - foobar-api.foobar
    - foobar-api.foobar.svc
    - foobar-api.foobar.svc.cluster.local

  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048

  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: raimon
