apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  # Traefik
  - traefik/ingressroute.yaml
  - traefik/ingressroutetcp.yaml
  - traefik/ingressrouteudp.yaml
  - traefik/middlewares.yaml
  - traefik/middlewarestcp.yaml
  - traefik/serverstransports.yaml
  - traefik/tlsoptions.yaml
  - traefik/tlsstores.yaml
  - traefik/traefikservices.yaml

  # Cert Manager
  - cert-manager/certificaterequests.yaml
  - cert-manager/certificates.yaml
  - cert-manager/challenges.yaml
  - cert-manager/clusterissuers.yaml
  - cert-manager/issuers.yaml
  - cert-manager/orders.yaml

  # Trust Manager
  - trust-manager/bundles.yaml

  # Grafana Agent
  - grafana/agents.yaml
  - grafana/integrations.yaml
  - grafana/logsinstances.yaml
  - grafana/metricsinstances.yaml
  - grafana/podlogs.yaml
  - grafana/podmonitors.yaml
  - grafana/probes.yaml
  - grafana/servicemonitors.yaml
