apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - traefik/ingressroute.yaml
  - traefik/ingressroutetcp.yaml
  - traefik/ingressrouteudp.yaml
  - traefik/middlewares.yaml
  - traefik/middlewarestcp.yaml
  - traefik/serverstransports.yaml
  - traefik/tlsoptions.yaml
  - traefik/tlsstores.yaml
  - traefik/traefikservices.yaml
