apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - traefik-proxy/deployment.yaml
  - traefik-proxy/ingress-class.yaml
  - traefik-proxy/pdb.yaml
  - traefik-proxy/rbac.yaml
  - traefik-proxy/service-api.yaml
  - traefik-proxy/service-lb.yaml
