apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - traefik-proxy/config.yaml
  - traefik-proxy/deployment.yaml
  - traefik-proxy/ingress-class.yaml
  - traefik-proxy/monitor.yaml
  - traefik-proxy/pdb.yaml
  - traefik-proxy/rbac.yaml
  - traefik-proxy/services.yaml
  - routes/api.raimon.dev.yaml
