apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: trust-manager
  namespace: kube-security
spec:
  interval: 5m
  releaseName: trust-manager
  maxHistory: 2
  chart:
    spec:
      chart: trust-manager
      version: 0.4.0
      interval: 10m
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: kube-security
  values:
    crds:
      enabled: false

    app:
      trust:
        namespace: kube-security
      metrics:
        service:
          servicemonitor:
            enabled: true
            labels:
              app.kubernetes.io/agent: grafana

    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
