apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - helm-release-cert-manager.yaml
  - helm-release-trust-manager.yaml
  - helm-repo-jetstack.yaml
  - tls-letsencrypt.yaml
  - tls-raimon.yaml
