apiVersion: v1
kind: Pod
metadata:
  name: netshoot
  namespace: foobar
spec:
  containers:
    - name: netshoot
      image: nicolaka/netshoot
      imagePullPolicy: Always
      args:
        - sh

      tty: true
      stdin: true
      stdinOnce: true

      volumeMounts:
        - name: raimon-ca
          readOnly: true
          mountPath: /ca

        - name: netshoot-certs
          readOnly: true
          mountPath: /certs

  volumes:
    - name: raimon-ca
      configMap:
        name: raimon-ca

    - name: netshoot-certs
      secret:
        secretName: foobar-mtls-client
