apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-agent-operator
  namespace: kube-observability
  labels:
    app.kubernetes.io/name: grafana-agent
    app.kubernetes.io/instance: grafana-agent-operator
    app.kubernetes.io/component: observability
    app.kubernetes.io/part-of: grafana
    app.kubernetes.io/managed-by: flux
spec:
  replicas: 1
  minReadySeconds: 10
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana-agent
      app.kubernetes.io/instance: grafana-agent-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grafana-agent
        app.kubernetes.io/instance: grafana-agent-operator
        app.kubernetes.io/component: observability
        app.kubernetes.io/part-of: grafana
        app.kubernetes.io/managed-by: flux
    spec:
      serviceAccountName: grafana-agent-operator
      containers:
        - name: grafana-agent-operator
          image: grafana/agent-operator:v0.26.1
          imagePullPolicy: IfNotPresent
          args:
            - --kubelet-service=default/kubelet

          ports:
            - name: metrics
              protocol: TCP
              containerPort: 8080

          resources:
            limits:
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 100Mi
