apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: grafana-agent-operator
  namespace: kube-observability
  labels:
    app.kubernetes.io/name: grafana-agent
    app.kubernetes.io/instance: grafana-agent-operator
    app.kubernetes.io/component: observability
    app.kubernetes.io/part-of: grafana
    app.kubernetes.io/managed-by: flux
    app.kubernetes.io/agent: grafana
spec:
  namespaceSelector:
    matchNames:
      - kube-network

  selector:
    matchLabels:
      app.kubernetes.io/name: grafana-agent
      app.kubernetes.io/instance: grafana-agent-operator

  endpoints:
    - path: /metrics
      port: metrics
