apiVersion: v1
kind: Service
metadata:
  name: grafana-agent-operator
  namespace: kube-observability
  labels:
    app.kubernetes.io/name: grafana-agent
    app.kubernetes.io/instance: grafana-agent-operator
    app.kubernetes.io/component: observability
    app.kubernetes.io/part-of: grafana
    app.kubernetes.io/managed-by: flux
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: grafana-agent
    app.kubernetes.io/instance: grafana-agent-operator
