apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: foobar
  namespace: flux-system
spec:
  path: "./kubernetes/production/eu-west9/foobar"
  prune: true
  interval: 10m
  targetNamespace: foobar
  sourceRef:
    kind: GitRepository
    name: foobar-infra
