apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kube-security
  namespace: flux-system
spec:
  path: "./kubernetes/production/eu-west9/kube-security"
  prune: true
  interval: 10m
  targetNamespace: kube-security
  sourceRef:
    kind: GitRepository
    name: foobar-infra
  dependsOn:
    - name: crds
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-variables
  healthChecks:
    # Cert Manager is UP and Running
    - apiVersion: apps/v1
      kind: Deployment
      name: cert-manager
      namespace: kube-security

    # Trust Manager is UP and Running
    - apiVersion: apps/v1
      kind: Deployment
      name: trust-manager
      namespace: kube-security

    # Our self signed Certificate Authority is here
    - apiVersion: v1
      kind: Secret
      name: raimon-ca
      namespace: kube-security

    # Our CA Bundle is ready
    - apiVersion: v1
      kind: ConfigMap
      name: raimon-ca
      namespace: kube-security
