apiVersion: v1
kind: Service
metadata:
  name: traefik-proxy-api
  namespace: kube-network
  labels:
    app.kubernetes.io/name: traefik-proxy
    app.kubernetes.io/instance: traefik-proxy-api
    app.kubernetes.io/component: network
    app.kubernetes.io/part-of: traefik
    app.kubernetes.io/managed-by: flux
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9100
      protocol: TCP
      targetPort: 9100
    - name: traefik
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app.kubernetes.io/name: traefik-proxy
    app.kubernetes.io/instance: traefik-proxy
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-proxy-lb
  namespace: kube-network
  labels:
    app.kubernetes.io/name: traefik-proxy
    app.kubernetes.io/instance: traefik-proxy-lb
    app.kubernetes.io/component: network
    app.kubernetes.io/part-of: traefik
    app.kubernetes.io/managed-by: flux
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8000
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    app.kubernetes.io/name: traefik-proxy
    app.kubernetes.io/instance: traefik-proxy
