apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foobar-api-cert
  namespace: foobar
  labels:
    app.kubernetes.io/name: foobar-api
    app.kubernetes.io/instance: foobar-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: foobar
    app.kubernetes.io/managed-by: flux
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
