apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: foobar-api
  namespace: foobar
  labels:
    app.kubernetes.io/name: foobar-api
    app.kubernetes.io/instance: foobar-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: foobar
    app.kubernetes.io/managed-by: flux
spec:
  replicas: 2
  serviceName: foobar-api
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: foobar-api
      app.kubernetes.io/instance: foobar-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: foobar-api
        app.kubernetes.io/instance: foobar-api
        app.kubernetes.io/component: api
        app.kubernetes.io/part-of: foobar
        app.kubernetes.io/managed-by: flux
    spec:
      imagePullSecrets:
        - name: ghcr
      initContainers:
        - name: copy-certs
          image: busybox:1.28
          command: ["/bin/sh"]
          args:
            - -c
            - "cp /certs/tls.crt /cache/cert.pem && cp /certs/tls.key /cache/key.pem"

          volumeMounts:
            - name: tls-certs
              mountPath: /certs
              readOnly: true
            - name: tls-cache
              mountPath: /cache
              readOnly: false

      containers:
        - name: foobar-api
          image: ghcr.io/barolab/foobar-api:0.1.3
          ports:
            - name: https
              protocol: TCP
              containerPort: 80

          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

            - name: WHOAMI_NAME
              value: "$(POD_NAME).$(POD_NAMESPACE).pod.cluster.local"

          resources:
            requests:
              memory: 32Mi
              cpu: 100m
            limits:
              memory: 32Mi
              cpu: 100m

          readinessProbe:
            tcpSocket:
              port: 80

          livenessProbe:
            tcpSocket:
              port: 80

          volumeMounts:
            - name: tls-cache
              mountPath: /cert
              readOnly: true

      volumes:
        - name: tls-certs
          secret:
            secretName: foobar-api-server

  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: tls-cache
      spec:
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
