apiVersion: monitoring.grafana.com/v1alpha1
kind: GrafanaAgent
metadata:
  name: grafana-agent
  namespace: kube-observability
  labels:
    app.kubernetes.io/name: grafana-agent
    app.kubernetes.io/instance: grafana-agent
    app.kubernetes.io/component: observability
    app.kubernetes.io/part-of: grafana
    app.kubernetes.io/managed-by: flux
spec:
  image: grafana/agent:v0.26.1
  serviceAccountName: grafana-agent
  integrations:
    selector:
      matchLabels:
        app.kubernetes.io/agent: grafana

  logs:
    instanceSelector:
      matchLabels:
        app.kubernetes.io/agent: grafana

  metrics:
    scrapeInterval: 60s
    externalLabels:
      cluster: ${gcp_cluster}
      project: ${gcp_project}
      region: ${gcp_region}
    instanceSelector:
      matchLabels:
        app.kubernetes.io/agent: grafana
