apiVersion: v1
kind: Secret
metadata:
  name: grafana-agent-metrics
  namespace: kube-observability
  labels:
    app.kubernetes.io/name: grafana-agent
    app.kubernetes.io/instance: grafana-agent
    app.kubernetes.io/component: observability
    app.kubernetes.io/part-of: grafana
    app.kubernetes.io/managed-by: flux
    app.kubernetes.io/agent: grafana
type: Opaque
data:
  password: "${grafana_prometheus_password}"
  username: "${grafana_prometheus_username}"
---
apiVersion: monitoring.grafana.com/v1alpha1
kind: MetricsInstance
metadata:
  name: grafana-agent-metrics
  namespace: kube-observability
  labels:
    app.kubernetes.io/name: grafana-agent
    app.kubernetes.io/instance: grafana-agent
    app.kubernetes.io/component: observability
    app.kubernetes.io/part-of: grafana
    app.kubernetes.io/managed-by: flux
    app.kubernetes.io/agent: grafana
spec:
  podMonitorNamespaceSelector: {}
  podMonitorSelector:
    matchLabels:
      app.kubernetes.io/agent: grafana

  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector:
    matchLabels:
      app.kubernetes.io/agent: grafana

  remoteWrite:
    - url: "${grafana_prometheus_url}"
      basicAuth:
        password:
          key: password
          name: grafana-agent-metrics
        username:
          key: username
          name: grafana-agent-metrics
