apiVersion: monitoring.grafana.com/v1alpha1
kind: Integration
metadata:
  name: grafana-agent-event-handler
  namespace: kube-observability
  labels:
    app.kubernetes.io/name: grafana-agent
    app.kubernetes.io/instance: grafana-agent
    app.kubernetes.io/component: observability
    app.kubernetes.io/part-of: grafana
    app.kubernetes.io/managed-by: flux
    app.kubernetes.io/agent: grafana
spec:
  name: eventhandler
  type:
    unique: true
  config:
    cache_path: /etc/eventhandler/eventhandler.cache
    logs_instance: kube-observability/grafana-agent-logs

  volumeMounts:
    - name: event-handler
      mountPath: /etc/eventhandler

  volumes:
    - name: event-handler
      persistentVolumeClaim:
        claimName: grafana-agent-event-handler
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-agent-event-handler
  namespace: kube-observability
  labels:
    app.kubernetes.io/name: grafana-agent
    app.kubernetes.io/instance: grafana-agent
    app.kubernetes.io/component: observability
    app.kubernetes.io/part-of: grafana
    app.kubernetes.io/managed-by: flux
    app.kubernetes.io/agent: grafana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
