apiVersion: monitoring.grafana.com/v1alpha1
kind: Integration
metadata:
  name: node-exporter
  namespace: kube-observability
  labels:
    app.kubernetes.io/name: grafana-agent
    app.kubernetes.io/instance: grafana-agent
    app.kubernetes.io/component: observability
    app.kubernetes.io/part-of: grafana
    app.kubernetes.io/managed-by: flux
    app.kubernetes.io/agent: grafana
spec:
  name: node_exporter
  config:
    procfs_path: host/proc
    rootfs_path: /host/root
    sysfs_path: /host/sys
    autoscrape:
      enable: true
      metrics_instance: kube-observability/grafana-agent-metrics
  type:
    allNodes: true
    unique: true

  volumeMounts:
    - name: rootfs
      mountPath: /host/root
    - name: sysfs
      mountPath: /host/sys
    - name: procfs
      mountPath: /host/proc

  volumes:
    - name: rootfs
      hostPath:
        path: /
    - name: sysfs
      hostPath:
        path: /sys
    - name: procfs
      hostPath:
        path: /proc
